### ISSUE TITLE
no issue

### ISSUE THREAD

**Issue by lazyoop** [xwlcn/Dodder#11]

**Comment by mm-lang** [comment]
尝试执行mvn package后遇到了这些错误
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for cc.dodder:dht-server:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springframework.boot:spring-boot-configuration-processor:jar -> duplicate declaration of version (?) @ line 56, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] dodder                                                             [pom]
[INFO] dodder-common                                                      [jar]
[INFO] dht-server                                                         [jar]
[INFO] torrent-download-service                                           [jar]
[INFO] dodder-api                                                         [jar]
[INFO] torrent-store-service                                              [jar]
[INFO] dodder-web                                                         [jar]
[INFO] 
[INFO] --------------------------< cc.dodder:dodder >--------------------------
[INFO] Building dodder 1.0-SNAPSHOT                                       [1/7]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] ----------------------< cc.dodder:dodder-common >-----------------------
[INFO] Building dodder-common 1.0-SNAPSHOT                                [2/7]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dodder 1.0-SNAPSHOT:
[INFO] 
[INFO] dodder ............................................. SUCCESS [  0.016 s]
[INFO] dodder-common ...................................... FAILURE [  0.676 s]
[INFO] dht-server ......................................... SKIPPED
[INFO] torrent-download-service ........................... SKIPPED
[INFO] dodder-api ......................................... SKIPPED
[INFO] torrent-store-service .............................. SKIPPED
[INFO] dodder-web ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.536 s
[INFO] Finished at: 2021-04-06T21:03:22+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dodder-common: Could not resolve dependencies for project cc.dodder:dodder-common:jar:1.0-SNAPSHOT: Failed to collect dependencies at net.sourceforge.cpdetector:cpdetector:jar:1.0.7: Failed to read artifact descriptor for net.sourceforge.cpdetector:cpdetector:jar:1.0.7: Could not transfer artifact net.sourceforge.cpdetector:cpdetector:pom:1.0.7 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [nuiton (http://maven.nuiton.org/release/, default, releases+snapshots), nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public, default, releases+snapshots)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :dodder-common

**Comment by mm-lang** [comment]
这是下载完pom.xml后遇到的错误

**Comment by mm-lang** [comment]
尝试执行mvn clean package也是像上面一样的错误

**Comment by mm-lang** [comment]
Google一顿子后感觉应该是cpdetector-1.0.7.pom这些东西不存在了

**Comment by mm-lang** [comment]
去相应的网站也没有找到cpdetector-1.0.7.pom这些文件

**Comment by mm-lang** [comment]
弄完一个又一个，好多依赖这东西都不存在了，自己添加了一些仓库，感觉麻烦死了，得弄到啥时候才是个头

**Comment by mm-lang** [comment]
弄成jar后dodder-api,dodder-common没法运行，dodder-common-1.0-SNAPSHOT.jar中没有主清单属性，dodder-api-1.0-SNAPSHOT.jar中没有主清单属性

**大佬能否发个弄好的成品**
**救救孩子吧**

**Comment by xwlcn** [comment]
修改`root` pom.xml的`repositories`:
```
<repositories>
        <repository>
            <id>nexus-ebi</id>
            <name>Nexus ebi</name>
            <url>https://www.ebi.ac.uk/intact/maven/nexus/content/repositories/public/</url>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
        </repository>
    </repositories>
```
再将`dodder-common`中pom.xml的`cpdetector`改为如下：
```
<dependency>
            <groupId>cpdetector</groupId>
            <artifactId>cpdetector</artifactId>
            <version>1.0.7</version>
        </dependency>
```
不会`java`的话不建议玩这个，这个项目打包倒是次要的，一些环境安装比这要复杂。对机器的要求也比较高。

**Comment by mm-lang** [comment]
能否直接给现成的可执行的.jar文件，我弄够了，所有环境都弄好了，就差dodder-api，dodder-common了  运行环境x86架构的64位系统

**Comment by xwlcn** [comment]
> 能否直接给现成的可执行的.jar文件，我弄够了，所有环境都弄好了，就差dodder-api，dodder-common了 运行环境x86架构的64位系统

[https://github.com/xwlcn/Dodder/releases/tag/v1.0.1-beta](https://github.com/xwlcn/Dodder/releases/tag/v1.0.1-beta)

**Comment by mm-lang** [comment]
谢大佬

**Comment by mm-lang** [comment]
> > 能否直接给现成的可执行的.jar文件，我弄够了，所有环境都弄好了，就差dodder-api，dodder-common了 运行环境x86架构的64位系统
> 
> https://github.com/xwlcn/Dodder/releases/tag/v1.0.1-beta

对不起打扰了，我还有一些问题
下载您给的打包好的文件后，dht-server-1.0-SNAPSHOT.jar执行时好像出错了，其他的都能运行
**运行环境：** Ubuntu18.04 x64 
Java版本java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

javac环境:javac 1.8.0_281

**执行命令：**  sudo java -jar dht-server-1.0-SNAPSHOT.jar

**执行结果：**
___  __ \___________  /_____  /____________
__  / / /  __ \  __  /_  __  /_  _ \_  ___/
_  /_/ // /_/ / /_/ / / /_/ / /  __/  /
/_____/ \____/\__,_/  \__,_/  \___//_/

 :: Dodder ::        (1.0-SNAPSHOT)

2021-04-22 16:48:25.221  INFO 36881 --- [           main] c.dodder.dhtserver.DhtServerApplication  : Starting DhtServerApplication v1.0-SNAPSHOT on ubuntu-virtual-machine with PID 36881 (/home/ubuntu/桌面/dodder/dht-server-1.0-SNAPSHOT.jar started by root in /home/ubuntu/桌面/dodder)
2021-04-22 16:48:25.228  INFO 36881 --- [           main] c.dodder.dhtserver.DhtServerApplication  : No active profile set, falling back to default profiles: default
2021-04-22 16:48:26.304  INFO 36881 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-04-22 16:48:26.307  INFO 36881 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2021-04-22 16:48:26.362  INFO 36881 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 24ms. Found 0 repository interfaces.
2021-04-22 16:48:26.768  INFO 36881 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2021-04-22 16:48:26.775  INFO 36881 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'taskScheduler' has been explicitly defined. Therefore, a default ThreadPoolTaskScheduler will be created.
2021-04-22 16:48:26.786  INFO 36881 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2021-04-22 16:48:26.879  INFO 36881 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.kafka.annotation.KafkaBootstrapConfiguration' of type [org.springframework.kafka.annotation.KafkaBootstrapConfiguration$$EnhancerBySpringCGLIB$$a21ad842] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-04-22 16:48:26.919  INFO 36881 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationDisposableAutoCreatedBeans' of type [org.springframework.integration.config.annotation.Disposables] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-04-22 16:48:26.954  INFO 36881 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration$$EnhancerBySpringCGLIB$$395a81ee] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-04-22 16:48:26.988  INFO 36881 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration$IntegrationJmxConfiguration' of type [org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration$IntegrationJmxConfiguration$$EnhancerBySpringCGLIB$$14ec8d0e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-04-22 16:48:27.022  INFO 36881 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration' of type [org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration$$EnhancerBySpringCGLIB$$4dd435db] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-04-22 16:48:27.119  INFO 36881 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mbeanServer' of type [com.sun.jmx.mbeanserver.JmxMBeanServer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-04-22 16:48:28.721  INFO 36881 --- [           main] cc.dodder.dhtserver.netty.DHTServer      : Starting dht server at 0.0.0.0/0.0.0.0:6688
2021-04-22 16:48:28.786  WARN 36881 --- [ntLoopGroup-4-1] io.netty.channel.ChannelInitializer      : Failed to initialize a channel. Closing: [id: 0xf2173e1f]

java.lang.NullPointerException: null
	at io.netty.channel.DefaultChannelHandlerContext.<init>(DefaultChannelHandlerContext.java:26) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.newContext(DefaultChannelPipeline.java:120) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:204) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:195) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at cc.dodder.dhtserver.netty.config.DHTChannelInitializer.initChannel(DHTChannelInitializer.java:21) ~[classes!/:1.0-SNAPSHOT]
	at cc.dodder.dhtserver.netty.config.DHTChannelInitializer.initChannel(DHTChannelInitializer.java:11) ~[classes!/:1.0-SNAPSHOT]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:613) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1475) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1127) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:654) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:503) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:416) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:475) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_281]

2021-04-22 16:48:28.790  WARN 36881 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'DHTChannelInitializer': Unsatisfied dependency expressed through field 'dhtServerHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'DHTServerHandler': Unsatisfied dependency expressed through field 'dhtServer'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'DHTServer': Invocation of init method failed; nested exception is java.nio.channels.ClosedChannelException
2021-04-22 16:48:28.841  INFO 36881 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-04-22 16:48:28.845 ERROR 36881 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'DHTChannelInitializer': Unsatisfied dependency expressed through field 'dhtServerHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'DHTServerHandler': Unsatisfied dependency expressed through field 'dhtServer'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'DHTServer': Invocation of init method failed; nested exception is java.nio.channels.ClosedChannelException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:598) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:847) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.9.RELEASE.jar!/:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.9.RELEASE.jar!/:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.9.RELEASE.jar!/:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.1.9.RELEASE.jar!/:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) [spring-boot-2.1.9.RELEASE.jar!/:2.1.9.RELEASE]
	at cc.dodder.dhtserver.DhtServerApplication.main(DhtServerApplication.java:15) [classes!/:1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_281]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [dht-server-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [dht-server-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [dht-server-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [dht-server-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'DHTServerHandler': Unsatisfied dependency expressed through field 'dhtServer'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'DHTServer': Invocation of init method failed; nested exception is java.nio.channels.ClosedChannelException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:598) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1255) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:595) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	... 26 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'DHTServer': Invocation of init method failed; nested exception is java.nio.channels.ClosedChannelException
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1255) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:595) ~[spring-beans-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	... 39 common frames omitted
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:958) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(AbstractChannel.java:977) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:532) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.42.Final.jar!/:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_281]

**Comment by mm-lang** [comment]
执行完后就退出了

**Comment by mm-lang** [comment]
还有一个问题，执行dht-server-1.0-SNAPSHOT.jar退出后 elasticsearch会被杀死，重新启动elasticsearch要先关闭torrent-store-service-1.0-SNAPSHOT.jar
